source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.6'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.1'

# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'

# Use Puma as the app server
gem 'puma', '~> 4.3'

# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.2'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'

# Optimized JSON
gem 'oj'

# Use Active Storage variant
gem 'image_processing', '~> 1.2'

# The official AWS SDK for Ruby
gem 'aws-sdk-s3'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Exception tracking and logging to Rollbar
gem 'rollbar'

# Taming Rails' Default Request Logging
gem 'lograge'

# Automatically strips all attributes of leading and trailing whitespace before validation
gem 'strip_attributes'

# The ultimate pagination ruby gem
gem 'pagy'

# Flexible authentication solution for Rails with Warden
gem 'devise'

# Rack Middleware for handling Cross-Origin Resource Sharing (CORS), which makes cross-origin AJAX possible.
gem 'rack-cors', require: 'rack/cors'

# The authorization Gem for Ruby on Rails
gem 'cancancan'

# An ActiveRecord plugin for managing lists
gem 'acts_as_list'
