source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.4.2'

# Full-stack web application framework. (https://rubyonrails.org)
gem 'rails', '~> 8.0.0'

# Sprockets Rails integration (https://github.com/rails/sprockets-rails)
gem 'sprockets-rails'

# Use Vite in Rails and bring joy to your JavaScript experience (https://github.com/ElMassimo/vite_ruby)
gem 'vite_rails'

# A modest JavaScript framework for the HTML you already have. (https://stimulus.hotwired.dev)
gem 'stimulus-rails'

# Pg is the Ruby interface to the PostgreSQL RDBMS (https://github.com/ged/ruby-pg)
gem 'pg', '~> 1.1'

# A Ruby/Rack web server built for parallelism. (https://puma.io)
gem 'puma', '~> 6'

# The speed of a single-page web application without having to write any JavaScript. (https://github.com/hotwired/turbo-rails)
gem 'turbo-rails'

# Sass adapter for the Rails asset pipeline. (https://github.com/rails/sass-rails)
gem 'sass-rails', '>= 6'

# Create JSON structures via a Builder-style DSL (https://github.com/rails/jbuilder)
gem 'jbuilder'

# A fast JSON parser and serializer. (http://www.ohler.com/oj)
gem 'oj'

# JSON Implementation for Ruby (https://ruby.github.io/json)
gem 'json'

# High-level wrapper for processing images for the web with ImageMagick or libvips. (https://github.com/janko/image_processing)
gem 'image_processing', '~> 1.2'

# Boot large ruby/rails apps faster (https://github.com/Shopify/bootsnap)
gem 'bootsnap', require: false

# Error reports you can be happy about. (https://www.honeybadger.io/for/ruby/)
gem 'honeybadger'

# Tame Rails' multi-line logging into a single line per request (https://github.com/roidrage/lograge)
gem 'lograge'

# The best pagination ruby gem (https://github.com/ddnexus/pagy)
gem 'pagy'

# Flexible authentication solution for Rails with Warden (https://github.com/heartcombo/devise)
gem 'devise'

# Middleware for enabling Cross-Origin Resource Sharing in Rack apps (https://github.com/cyu/rack-cors)
gem 'rack-cors'

# Block & throttle abusive requests (https://github.com/rack/rack-attack)
gem 'rack-attack'

# Rack middleware for defining a canonical host name. (https://github.com/tylerhunt/rack-canonical-host)
gem 'rack-canonical-host'

# Brotli compression for Rack responses (http://github.com/marcotc/rack-brotli/)
gem 'rack-brotli'

# Slim templates generator for Rails (https://github.com/slim-template/slim-rails)
gem 'slim-rails'

# A framework for building reusable, testable & encapsulated view components in Ruby on Rails. (https://viewcomponent.org)
gem 'view_component'

# Simple HTTP and REST client for Ruby, inspired by microframework syntax for specifying actions. (https://github.com/rest-client/rest-client)
gem 'rest-client'

# Simple, efficient background processing for Ruby (https://sidekiq.org)
gem 'sidekiq'

# Markdown that smells nice (https://github.com/vmg/redcarpet)
gem 'redcarpet'

# A comprehensive slugging and pretty-URL plugin. (https://github.com/norman/friendly_id)
gem 'friendly_id'

# SSL/TLS and general-purpose cryptography for Ruby (https://github.com/ruby/openssl)
gem 'openssl'
