source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 2.7'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.2', '>= 6.0.2.2'

# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'

# Use Puma as the app server
gem 'puma', '~> 4.1'

# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'

# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 5.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'

# Optimized JSON
gem 'oj'

# Use Active Storage variant
gem 'image_processing', '~> 1.2'

# The official AWS SDK for Ruby
gem 'aws-sdk-s3'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Exception tracking and logging to Rollbar
gem 'rollbar'

# Taming Rails' Default Request Logging
gem 'lograge'

# Automatically strips all attributes of leading and trailing whitespace before validation
gem 'strip_attributes'

# The ultimate pagination ruby gem
gem 'pagy'

# A modern, responsive admin framework for Ruby on Rails
gem 'trestle'

# Flexible authentication solution for Rails with Warden
gem 'devise'

# Barebones two-factor authentication with Devise
gem 'devise-two-factor'

# Rack Middleware for handling Cross-Origin Resource Sharing (CORS), which makes cross-origin AJAX possible.
gem 'rack-cors', require: 'rack/cors'

# Rack middleware for blocking & throttling
gem 'rack-attack'

# Rack middleware for defining a canonical host name.
gem 'rack-canonical-host'

# The authorization Gem for Ruby on Rails
gem 'cancancan'

# An ActiveRecord plugin for managing lists
gem 'acts_as_list'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
gem 'turbolinks_render'

# Template language whose goal is to reduce the syntax to the essential parts without becoming cryptic
gem 'slim'

# Simple HTTP and REST client for Ruby, inspired by microframework syntax for specifying actions
gem 'rest-client'

# Simple, efficient background processing for Ruby
gem 'sidekiq'

# Complete Ruby geocoding solution
gem 'geocoder'

# Search Engine Optimization (SEO) for Ruby on Rails applications
gem 'meta-tags'

# Intelligent search made easy with Rails and Elasticsearch
gem 'searchkick'

# The Rails adapter for Inertia.js
gem 'inertia_rails'

# The safe Markdown parser, reloaded
gem 'redcarpet'
